### ISSUE TITLE
Stop and restart only changed triggers

### ISSUE THREAD

**Issue by isaacs-gh** [Azure-Player/azure.datafactory.tools#264]
Is it possible for this enhanced deployment behavior to be added to this package?
See:
https://techcommunity.microsoft.com/t5/azure-data-factory-blog/ci-cd-improvements-related-to-pipeline-triggers-deployment/ba-p/3605064
and
https://github.com/Azure/Azure-DataFactory/blob/main/SamplesV2/ContinuousIntegrationAndDelivery/PrePostDeploymentScript.Ver2.ps1

**Comment by NowinskiK** [comment]
That's good idea, but covers triggers only. 
I have another planned task for the #adftools which is to make incremental deployment for whole ADF: https://github.com/SQLPlayer/azure.datafactory.tools/issues/195
