### ISSUE TITLE
Error while deploying to QA: "You cannot call a method on a null-valued expression"

### ISSUE THREAD

**Issue by SravanDodda** [Azure-Player/azure.datafactory.tools#271]
I am getting an error as stated in the subject line - this is happening while deploying from Dev to QA. Last month you have helped me with Build error (see bug#260. [adftools v0.110]. That is now resolved but am getting this new error

We are NOT using any global parameters

![image](https://user-images.githubusercontent.com/55965099/209891020-a68f0162-8520-4ad8-8c8e-f3d836dc4f9c.png)

![image](https://user-images.githubusercontent.com/55965099/209891040-ffff095a-a984-4ab2-bca9-11ba18962038.png)

Please let me know what else I can provide you to help me with this

Appreciate the help in advance

**Comment by NowinskiK** [comment]
It sounds like wrong config file

**Comment by SravanDodda** [comment]
> It sounds like wrong config file

Thank you for the reply. How to find the config file? This was developed by someone who is no longer with us

**Comment by NowinskiK** [comment]
Check out doc: https://github.com/Azure-Player/azure.datafactory.tools
