### ISSUE TITLE
whitespace is removed during deployment

### ISSUE THREAD

**Issue by regisbaccaro** [Azure-Player/azure.datafactory.tools#274]
I am deploying ADF using DevOps pipeline,
lately I have observed that when I look at the result of the deployment all whitespace is removed from ADF.

- All activities name have no whitespace in their names or properties. i.e before deployment 'Get Latest Date', after deployment 'GetLatestDate'
- Linked services properties have no whitespace. i.e before deployment 'Initial Catalog', after deployment 'InitialCatalog' and therefore cannot connect to anything
- Queries in lookups have no whitespace. i.e SELECTOP1FROMdbo.person.

Deployment succeeds but all pipelines are not in runnable state.

Any suggestion about how that was introduced. My yaml code is very straightforward and the source repo has all the right whitespaces.

 - powershell: |
            Install-Module Az.DataFactory -Force 
            Install-Module -Name "azure.datafactory.tools" -Force
            Import-Module -Name "azure.datafactory.tools" -Force
          displayName: 'PowerShell Script'

        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: InlineScript'
          inputs:
            azureSubscription: $(azureSubscription)
            ScriptType: InlineScript
            Inline: |
              $adf = Import-AdfFromFolder -RootFolder "$(System.DefaultWorkingDirectory)" -FactoryName "$(dataFactoryName)"
              $opt = New-AdfPublishOption
              $opt.StopStartTriggers = $true
              $opt.CreateNewInstance  = $false
              $opt.DeleteNotInSource = $false
              $opt.DoNotStopStartExcludedTriggers = $true
              $opt.FailsWhenConfigItemNotFound = $true
              $opt.DoNotDeleteExcludedObjects = $true
              $opt.Excludes.Add("integrationRuntime.*", "")
              $opt.Excludes.Add("trigger.*", "")

              Publish-AdfV2FromJson -RootFolder "$(System.DefaultWorkingDirectory)" `
              -ResourceGroupName "$(RG)" -DataFactoryName "$(dataFactoryName)" `
              -Location "WestEurope" -Stage "$(System.DefaultWorkingDirectory)/deployment/stag-parameters.json" -Option $opt `

Thanks in advance
Régis Baccaro

**Comment by MarliesVeenes** [comment]
I encounter the same issue since yesterday. 
For me the workaround is to switch from the default method `AzResource` to the method `AzDataFactory` on the function `Publish-AdfV2FromJson`. 

It is explained [here](https://github.com/Azure-Player/azure.datafactory.tools#publishing-method) that its an unstable method, but for the moment gives better results than `AzRecource`.

**Comment by NowinskiK** [comment]
Hello @regisbaccaro, my friend!
Thanks for raising the ticket here.

This issue has nothing to do with #adftools , the problem was created by Microsoft some time ago.
Please check this thread: **Tool removing all spaces from code** #265

Let me know if this resolved the problem. It should.
