### ISSUE TITLE
Addition of Dependency in rules

### ISSUE THREAD

**Issue by ajit2525** [Azure-Player/azure.datafactory.tools#277]
**Is your feature request related to a problem? Please describe.**
Is it possible to bring new feature like every time we have to give the objects name independently, instead of that lets say we give pipeline name in include rule and it will pick its dependency while deployments.

**Describe the solution you'd like**
Lets say we have 3 pipelines to deploy. and total 5 pipeline json codes are there. So is it not possible that we give the pipeline name in include rule and it will pick its dataset,linked services etc.

Similar if we give pipeline names in exclude rule and it will ignore its dependency objects while deployments.

**Describe alternatives you've considered**
The existing rules file with independently adding all objects to include or exclude

**Additional context**
NA

**Comment by NowinskiK** [comment]
I'm not planning any extension to the logic like this (edge case scenario, sorry).
However, you can always build it on your own as a script and include/exclude any required objects in the collection.
