### ISSUE TITLE
Validates all JSON files of ADF failed for special character

### ISSUE THREAD

**Issue by dzfstephen** [Azure-Player/azure.datafactory.tools#287]
hello Kamil ,

Sorry about previous ticket that missing info. 

I put more info into this one. hopeful it makes sense to you and you can help me to fix this issue. 

This issues happens when it is trying validate a dataset Json file. 

The dataset Json file includes a special character in one property.

````
	"RFP": {
								"type": "object",
								"properties": {
									"In last 12 months": {
										"type": "object",
										"properties": {
											"Recently used": {
												"type": "integer"
											},
											**"RFP's Involved": {**
												"type": "string"
											}
										}
									}
								}
							}
``````
![image](https://user-images.githubusercontent.com/38846620/221045256-d3ffa21f-fbd7-4ef1-8b53-c652cda35bce.png)

![image](https://user-images.githubusercontent.com/38846620/221047134-6419b057-2514-46fb-b6fd-f8d56fe5dcf5.png)

the error is like this
![image](https://user-images.githubusercontent.com/38846620/221046112-63b9e8cf-6106-420e-96fc-6a63c86c0de5.png)

Please let me know if more info is required. 

Thanks & Regards

**Comment by NowinskiK** [comment]
Fixed and released in [ver.1.2](https://github.com/Azure-Player/azure.datafactory.tools/releases/tag/v1.2)
