### ISSUE TITLE
##[error]ADFT0029: Unknown object type: BigDataPool.

### ISSUE THREAD

**Issue by LiquoriChris** [Azure-Player/azure.datafactory.tools#289]
Hello Kamil,

Thank for you adding the new notebook activity type. However, we are receiving an additional error when deploying the new notebook activity. This is for when using a `bigDataPool` in synapse (Dedicated SQL Pool).

Error: `##[error]ADFT0029: Unknown object type: BigDataPool.`

Thanks.

**Comment by NowinskiK** [comment]
Released in ver.1.3
