### ISSUE TITLE
Using self-hosted agent VM for "Publish Azure Data Factory" task

### ISSUE THREAD

**Issue by akg4281** [Azure-Player/azure.datafactory.tools#294]
Hello,
   We are testing the SQL player task "Publish Azure Data Factory" on a self-hosted agent VM.
The AZ and azure.datafactory.tools power shell modules are installed on the VM.

But when executing the task, it is failing with the below error:-

##[error]Cannot find type [AdfPublishOption]: verify that the assembly containing this type is loaded.

Tried in the power shell prompt as below and it throws the same error:-

PS C:\> New-AdfPublishOption
New-Object : Cannot find type [AdfPublishOption]: verify that the assembly containing this type is loaded.
At line:32 char:18
+         return @(& $origNewObject @psBoundParameters)
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

PS C:\>
PS C:\>
PS C:\>Get-Module -Name azure.datafactory.tools

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.0      azure.datafactory.tools             {Export-AdfToArmTemplate, Get-AdfDocDiagram, Get-AdfFromSe...

PS C:\>

Could you please provide some info if we are missing some steps here.

Thank you,

**Comment by NowinskiK** [comment]
Apparently the PS module is installed or imported incorrectly. 
Try to uninstall, install and import again.
