### ISSUE TITLE
[error]InputIsMalformedDetailed : Input is malformed. Reason: Could not get integration runtime details for 

### ISSUE THREAD

**Issue by gaurav-bhadauria22** [Azure-Player/azure.datafactory.tools#312]
Hello,
I have an Azure data factory V2 and I created a Linked service(Azure Synapse Analytics (Artifacts)) in Dev. Everything worked fine so I decided to move it to Production but my deployment failed with below error:
2023-05-03T10:02:15.1193371Z Start deploying object: [linkedService].[ls_AzureSynapseArtifacts] (1 dependency/ies)
2023-05-03T10:02:15.8430868Z ##[error]InputIsMalformedDetailed : Input is malformed. Reason: Could not get integration runtime details for IR-WEU-ManagedVnet

We have a config file which has entry for all the linked service crated earlier and it had entries like:

type	                name	                path	                                value
linkedService	ls_AzureKeyVault	typeProperties.baseUrl	$env:ENV_AKV_LS_properties_typeProperties_baseUr

I think there should an entry for this new linked service in this config file but I don't know what to put and where to put. Can you please help me with this?

**Comment by NowinskiK** [comment]
I can't help you having this poor information you provided.

**Comment by gaurav-bhadauria22** [comment]
Hello Nowinskis,

Thanks for your response. It was my first time asking the question so was not aware what information I should have provided.

However, today I managed to get it solved by adding a row with name and type only for this linked service in config file.
