### ISSUE TITLE
Retry option to avoid timed out on request

### ISSUE THREAD

**Issue by kripa-2019** [Azure-Player/azure.datafactory.tools#315]
While publishing to a Data factory, we intermittently see a time out error.

Is there a timeout clause baked into the task?

**Comment by NowinskiK** [comment]
Hi guys. Thanks for your comments. 
Are you able to create Pull Request with required changes?
That would help me to review and adopt it to the module.

**Comment by NowinskiK** [comment]
Closing as duplication of #295
