### ISSUE TITLE
Facing some issues in deploying async advanced properties 

### ISSUE THREAD

**Issue by sadammoulana** [Azure-Player/azure.datafactory.tools#323]
Hi 
I hope you are doing well and good
Actually we use the adf tools and powershell scripts to deploy our Azure data factory to higher environments.

But recently we added a web activity in one of our pipelines and we enable an advanced setting called "Disable Async Pattern" when we try to deploy the same to our UAT environment this specific setting is alone not getting updated in our Adf pipeline can you please guide me what should I do to enable this property using our devops pipeline Directly instead of doing it Manually everytime.

**Comment by NowinskiK** [comment]
Not enough information.
