### ISSUE TITLE
Incremental deployment not working as expected 

### ISSUE THREAD

**Issue by bentomtvkl123** [Azure-Player/azure.datafactory.tools#325]
**Describe the bug**
Incremental deployment in Publish ADF task showing 0 unchanged objects even if there are no changes in the objects and it is publishing everything.

**Expected behaviour**
If there is no change in the json files used, when using publish task with incremental deployment nothing should be published. But for everything is published and logs are showing 0 unchanged objects.

**Version of PowerShell module of:**
 - 5.1

**Comment by NowinskiK** [comment]
Prove.
