### ISSUE TITLE
loop on removing object when trigger and pipeline share the same name

### ISSUE THREAD

**Issue by rw72000** [Azure-Player/azure.datafactory.tools#326]
Hello,

We have here a scenario that should work but fails :
In dev :
Create a pipeline and call it "test"
Create a trigger that starts the pipeline "test" and call it 'test' also
Publish to prod environment using json method

then

Delete both pipeline and trigger in dev
publish to prod
-> removing pipeline is tried many times without error or warning until overflow happens

If trigger and pipeline have different names, there isn't any problem.
Can you fix ?

Regards

**Comment by NowinskiK** [comment]
Best practise is to keep names unique. 
This is minor known issue and there is no plan right now to fix it. 
AFAIR it was some issue with this to identify appropriate related object, hence no solution for this to date.
