### ISSUE TITLE
Enabling a specific setting in ADF using Azure DevOps

### ISSUE THREAD

**Issue by sadammoulana** [Azure-Player/azure.datafactory.tools#328]
Hi,

Recently I developed one ADF pipeline.
And in this pipeline I created one "WEB ACTIVITY" and enabled the following property in the settings 
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/73111345/db9a3dfa-bea8-4ae1-99d2-f9ca298c8af7)
But when i try to generate ARM TEMPLATES this specific activity alone is not generated there, because of this it is not getting reflected in higher environments also when I do the deployment.

I even tried to enable this manually in the higher environments but when we try to deploy the ADF again it is getting disabled automatically 

And I even tried ADF tools and PowerShell tasks to deploy the same and same problem there also 
Can you please suggest me something on how to deploy this property to higher environments using Azure Pipelines.

**Comment by NowinskiK** [comment]
Do you see this option in UI? I can't find it. If it's not there then might be unsupported yet.
