### ISSUE TITLE
State of the development branch?

### ISSUE THREAD

**Issue by jikuja** [Azure-Player/azure.datafactory.tools#329]
Looks like code in PRs https://github.com/Azure-Player/azure.datafactory.tools/pull/252 and https://github.com/Azure-Player/azure.datafactory.tools/pull/151 was never merged to master on 1.0 release.

Noticed it when I was trying to run `Test-AdfLinkedService.ps1` with 1.4.0 release.

**Comment by NowinskiK** [comment]
Thanks for raising it. Indeed. I will check that out.
ref #222
