### ISSUE TITLE
Git configuration lost for Target ADF environment after publish using adftools in release pipeline

### ISSUE THREAD

**Issue by siddvank** [Azure-Player/azure.datafactory.tools#330]
Hi @NowinskiK ,

I am facing similar issue, my changes are merged to collab branch from my feature branch. I am using adftools in my release pipeline to push my changes from collab branch to ADF-Dev(which is connected to Github repository). As soon as my release pipeline completes, my changes are published to ADF-Dev(live), but, when I reload the ADF portal, Git configuration is lost in ADF-Dev, and, ADF asks me to configure Git again. Is there anyway to preserve git configuration in target ADF after publishing changes using release pipeline?

**Comment by NowinskiK** [comment]
No one else raised this problem so far and I use the tool in multiple projects and also never faced that.

**Comment by NowinskiK** [comment]
Feel free to reopen this ticket providing steps to reproducing this issue, meanwhile I'm closing this ticket.
