### ISSUE TITLE
Test-AdfCode - ADFT0015: Type [credential] is not supported

### ISSUE THREAD

**Issue by stephennaughton** [Azure-Player/azure.datafactory.tools#331]
**Describe the bug**

Similar to [https://github.com/Azure-Player/azure.datafactory.tools/issues/156](https://github.com/Azure-Player/azure.datafactory.tools/issues/156)

I am attempting to parameterise the value assigned to an ADF Credential using a CSV configuration file. The credential type is a User Assigned Managed Identity. It looks like from my reading of previous issues that support for this was added recently.

I came across an issue when running "Test-AdfCode" on my ADF repo. The CSV file provided as the stage parameter includes something similar to the following:

    credential,CRD_UAMI_ADS,$.properties.typeProperties,"<JSON value including managed identity resource id>"

When I run Test-AdfCode on this pre-publish, I get the following:

    Validation of config file completed.
    ERROR: ADFT0015: Type [credential] is not supported.

This error is thrown in private/Get-AdfObjectByPattern.ps1 which looks like it doesn't support Credentials. However I notice that Credentials are supported in private/Get-AdfObjectByName.ps1

Am I correct in assuming that credentials are supported by the this tool? Is there something that I'm missing when setting the value in the CSV maybe?

Thank you for your time on this. 

**To Reproduce**
Your script to reproduce the behaviour:
```
Your script here
```

**Expected behaviour**

**Screenshots**

**Version of PowerShell module of:**
 - ver.........

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

**Comment by NowinskiK** [comment]
You're right. Credentials are now supported, so this is a bug.
