### ISSUE TITLE
Purview configuration gets overwritten when deploy Global Parameters using ADF deployment task

### ISSUE THREAD

**Issue by Spsutar** [Azure-Player/azure.datafactory.tools#343]
We deploy the below purview configuration using Bicep template via ADO pipeline along with ADF instance deployment.
But when ADF objects are deployed using ADF deployment task, this configuration gets removed. 
I have even tried creating this configuration manually on ADF portal. Also after this configuration added to the ADF portal (either manually or Bicep) and when you export the ARM template, this configuration does not show up in the ARM, or  in the git branch files. So we have no way to exclude overwriting it in the deployment task.

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/17762439/a8a5c478-7973-421a-b901-dff6bc558a1a)

**To Reproduce**
- Go to the Data factory portal - Manage tab and click on - **Connect to a Purview Account**
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/17762439/67dfecf3-2b03-4bf6-8927-fa0670f550ec)

- Select Subscription, Purview instance and click on apply
- 
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/17762439/d83672bf-f9e3-457b-a21a-75613a472cd6)
- This way the Purview can be configured manually. Now deploy ADF objects using the ADF deployment task.
- This will wipe out the Purview Config.
- 
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/17762439/56700ca8-042d-4195-9617-12c58eb08570)

```
Your script here
ADF deployment task looks like this:
 - task: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1
    displayName: 'Publish ADF Objects to ADF instance'
    inputs:
      azureSubscription: ${{ parameters.paramAzureSubscription }}
      ResourceGroupName: ${{ parameters.paramIngResourceGroupName }}
      DataFactoryName: ${{ parameters.paramfactoryName }}
      DataFactoryCodePath: $(Pipeline.Workspace)\drop
      Location: ${{ parameters.paramLocation }}
      IncrementalDeployment: true
      StageCode: ${{ parameters.environment }}
      CreateNewInstance: false
      FilteringType: Inline
      FilterText: |
       -integrationRuntime.*
       -managedVirtualNetwork*.*
       -*managedPrivateEndpoint.*
       -trigger.*


**Version of PowerShell module of:**
 - ver...NA......

**Provide all files to reproduce the issue**
Bicep code snippet to deploy the Purview Config via IaC

// Resources
resource datafactory 'Microsoft.DataFactory/factories@2018-06-01' = {
  name: datafactoryName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    globalParameters: !empty(adfglobalParameters) ? adfglobalParameters:{}   
    publicNetworkAccess: 'Disabled'
    purviewConfiguration: isPurviewdeployed ?{
      purviewResourceId: purviewId
    }:null
    repoConfiguration: env == 'dev'? {
      accountName: 'ADO-ORGName'
      collaborationBranch: 'develop'
      repositoryName: 'Repo'
      rootFolder: '/ADF'
      type: 'FactoryVSTSConfiguration'
      projectName: 'ADO-ProjectName'
    }:null
  }
}

**Comment by NowinskiK** [comment]
Resolved in ver.1.6.1 - currently in preview.
