### ISSUE TITLE
Incremental Deployment seems to not work when factory folder does not exist

### ISSUE THREAD

**Issue by MartaUch** [Azure-Player/azure.datafactory.tools#346]
Hello,

I was testing situation when there is no factory file and IncrementalDeployment and DeployGlobalParams are True.
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/77666fd6-90f9-47f7-a7e7-2f3e6e7f7045)
View on the Repos:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/4e7303d3-6db8-4ded-b279-b9c736fe0dad)
I would expect that new file will be created based on:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/1b489e7e-d3b4-4e9c-84af-c821cdc48cbb)
But I'm receiving the following error:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/360067cf-a6cb-462d-b5b0-96491b851d9f)

Best regards
Marta

**Comment by NowinskiK** [comment]
I can't reproduce the issue:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/13696b6a-2c5c-43c1-aca5-6bccd2d4cd17)

Check this example:
https://github.com/Azure-Player/azure.datafactory.tools/blob/6844dee2f81264cb1e9a345970c42e5ef890299f/adhoc/issue-195/test-195.ps1#L14C1-L27C1

**Comment by MartaUch** [comment]
Hmm but please correct me if I'm wrong, you actually have a folder called "factory", but it's empty. In this case you check in your code if there are no files, then create a new one and proceed with incremental deployment. 

In my case I don't have a folder at all in the repository. I can't avoid that, because even if I create the empty folder and later build the artifact, this folder will not be present, it just disappears. I checked it once again and still the same issue:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/737645c0-4928-476e-80aa-a53a07423823)
I'm not sure what else I'm missing.

**Comment by NowinskiK** [comment]
Got'ya! Yes, I had a folder but no file. The error is when you don't have a folder. ok.

**Comment by MartaUch** [comment]
Hi :)
I have one additional question regarding this bug.
Let's assume it is fixed. If a new file is created to keep information about the incremental deployment global parameter and there are already existing global parameters in the ADF instance. Will they be removed/overwritten after deployment or global parameter for incremental deployment will be just added without touching existing parameters?

**Comment by NowinskiK** [comment]
All global parameters are being deployed as a one consistent object, so will be overwritten.
