### ISSUE TITLE
option to only update object properties that are specified in Config file

### ISSUE THREAD

**Issue by dzfstephen** [Azure-Player/azure.datafactory.tools#349]
Good morning 

A pipeline is already in sandpit environment, and I want to update the existing pipeline properties, like updating an activity's name. I added it into the config file:
![image](https://user-images.githubusercontent.com/38846620/222271712-d57fc47b-65b1-4c0e-8e92-58eaadd90513.png)

First I did not add it in the rule text file, because the pipeline is already in sandpit environment, I only want to update the pipeline's property.  CICD pipeline run successfully, and it shows it pick up the updating request from the config file. see the snapshot
![image](https://user-images.githubusercontent.com/38846620/222272564-f25c0f0a-e02f-4a84-96a8-2c31ff1a2e0c.png)

However, when I log in to Azure Data factory, and checked the pipeline, I found the activity's name has not been updated, it is still same.
![image](https://user-images.githubusercontent.com/38846620/222272963-dc9de65e-a18f-4930-9790-131026c2d0e6.png)

Then I tried to add the pipeline into the Rules text file and the Config Json file. then it worked, it deployed the pipeline to Sandpit environment and then updated the activity name (in the config Json file).  however, it also replaced all other properties with old values, like other source datasets ( updated in previous CICD pipeline, not in the config Json file this time).  

Does that mean if I want to only update some properties for an existing object in an environment, I have to add it into the Rules text file to deploy it first.   is there an option to only update an existing object without to deploy it again first?

Thanks & Regards

Stephen

**Comment by NowinskiK** [comment]
Sorry, I'm not quite sure what you are trying to achieve here.
However, I can't see any error in the tool, hence removing flag "triage".
