### ISSUE TITLE
##[error]You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by SravanDodda** [Azure-Player/azure.datafactory.tools#354]
**Describe the bug**
When pushing Dev code to QA, get the error right after "Adding Global Parameter..". We are NOT using any Global Parameters. Initially I did not have parameter lines (as highlighted) and was getting error. So, I went ahead and added the two lines highlighted to see if it works but to no avail

You cannot call a method on a null-valued expression.

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/55965099/1d2568dd-2853-41bb-a19b-c81a8d8bb498)

**To Reproduce**

Changed QA config file to add the following lines but to no avail:

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/55965099/580a181a-8fe8-41ac-aa71-07eb8d867f57)

The config file did not have two lines before. I added them since I was getting the error. Even after adding these lines, it is not working

```
Your script here
```

**Expected behaviour**

Publishing to QA failing

**Screenshots**

Added error log and config file

**Version of PowerShell module of:**
 - ver.........1.*

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

[config-QA.csv](https://github.com/Azure-Player/azure.datafactory.tools/files/12134634/config-QA.csv)

[tasklog_6.log](https://github.com/Azure-Player/azure.datafactory.tools/files/12134615/tasklog_6.log)

**Comment by smndf** [comment]
Facing the same error.
It looks like the variable $targetAdf is not defined in https://github.com/Azure-Player/azure.datafactory.tools/blob/bd89b0ae8f3688506b0cfd7c2217bd9d93d9f86a/private/Deploy-AdfObjectOnly.ps1#L146
This part of the code was added in https://github.com/Azure-Player/azure.datafactory.tools/commit/1bda61412edfa32c9dca0394d3ad9dfc8416a16c

**Comment by SravanDodda** [comment]
@NowinskiK any help that you can provide?

**Comment by NowinskiK** [comment]
I see in the code that `$targetAdf` is not passed, hence the problem.
But weird is that in most cases (for many people including my tests) this is working as probably treats the parameter within wider scope.
Can you check with other agent's settings?
I can't investigate that deeper right now as I'm on holiday, but I'll do as soon as I can.

**Comment by SravanDodda** [comment]
> 

Thanks for the reply. Is your answer to my original question or another commenter's (@smndf)?

**Comment by SravanDodda** [comment]
I am now getting this:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/55965099/37790ab7-54d3-4d6b-b1dc-f289474f4396)

**Comment by SravanDodda** [comment]
Any timely help is appreciated

**Comment by NowinskiK** [comment]
Released in ver.1.7.0

**Comment by SravanDodda** [comment]
> Released in ver.1.7.0

Kamil,
I am still getting this error. Could you help?

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/55965099/b3bb2410-e688-42ab-b712-8e2e69c0a164)

**Comment by NowinskiK** [comment]
It has not been released yet in DevOps extension, only in PowerShell.
