### ISSUE TITLE
(500) Internal Server Error

### ISSUE THREAD

**Issue by sannicolao** [Azure-Player/azure.datafactory.tools#358]
Hi,
I receive a 500 Internal Server Error after updating global parameters. 

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/56923712/47ec01db-a4ea-4420-8fd5-4eeabd8c5a09)

to update the global parameter i have in my deployment.csv the following : 
factory,dg-RIMO-Int,"$.properties.globalParameters.'gp_kupo_base_url'.value","$($Env:KupoHost)"
factory,dg-RIMO-Int,"$.properties.globalParameters.'eDossier_RecordsCheck'.value","$($Env:eDossierRecordCheck)"

But as well without these lines, i receive the same error.

Thanks for help.

**Comment by NowinskiK** [comment]
It sounds like intermittent issue on API side. Do you still face this issue? If so - show more details by enabling diagnostic mode.

**Comment by sannicolao** [comment]
the error still occur. But only for that Azure Data Factory. For another Data Factory, the release works as expected. 
I deleted the whole ADF and try to create a new one, but get the error as well. 

Debug on: 
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/56923712/b2f2a05d-c864-4a12-bb02-e071d95a816e)

**Comment by NowinskiK** [comment]
Sorry, I can't reproduce this error. Also, no one else raised such issue. 
Share the code with me (ADF files and PS script) which I would be able to run and confirm that it not works.
