### ISSUE TITLE
pipelineReturnValue is not getting set as expected after deployment with PowerShell deployment

### ISSUE THREAD

**Issue by bharanigit** [Azure-Player/azure.datafactory.tools#373]
**Describe the bug**
We are using pipelineReturnValue  to get value from Databricks activity and assigning to a variable. 
pipelineReturnValue is not getting set as expected after deployment with PowerShell deployment

**To Reproduce**
<img width="466" alt="image" src="https://github.com/Azure-Player/azure.datafactory.tools/assets/28491939/746862f3-54ff-4fcf-8284-a31df1797614">

```json
"userProperties": [],
"typeProperties": {
    "variableName": "pipelineReturnValue",
    "value": [
        {
            "key": "templatecheck",
            "value": {
                "type": "Expression",
                "content": "@activity('Template Validation').output.runOutput"
            }
        }
    ],
```

**Expected behaviour**
Pipeline return value should get set correctly after deployment

**Screenshots**
<img width="466" alt="image" src="https://github.com/Azure-Player/azure.datafactory.tools/assets/28491939/473a0bcf-7438-428e-9a4d-79ba2cdcbe50">

Screenshot showing json (after deployment) not reflecting as in pipeline json:
<img width="911" alt="image" src="https://github.com/Azure-Player/azure.datafactory.tools/assets/28491939/9e425609-d5b5-4ad3-a617-db8ac16f6801">

**Version of PowerShell module of:**
 - ver......... >1.10.0

**Provide all files to reproduce the issue**
- Attach at least log file (you can wipe out any potentially sensitive info)
- Attach files of objects which are involved in the process

**Comment by bharanigit** [comment]
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28491939/6221d7c1-7a5e-4212-9a10-5681bb658cf1)
I have attached our pipeline json, if its too lengthy.. to replicate pls create one pipeline with pipeline return variable set as shown in above image and try to deploy using the pipeline using azure-player powershell module. 
[pipeline.txt](https://github.com/Azure-Player/azure.datafactory.tools/files/12608326/pipeline.txt)

**Comment by bharanigit** [comment]
Hi, I have uploaded pipline.txt in previous comment to reproduce the issue. pls let me know if it is sufficient.

**Comment by NowinskiK** [comment]
Not sufficient, unfortunately. I don't have spare time to build script to reproduce the issue, so please do so and share here.
