### ISSUE TITLE
Incremental deploy feature causes payload limit issue

### ISSUE THREAD

**Issue by anfredrick** [Azure-Player/azure.datafactory.tools#374]
We have an instance of data factory with close to 1000 objects. We tried to use the incremental deploy feature, the deployment went fine. But, the pipelines could not start and failed with ErrorCode=RequestContentTooLarge. Upon investigation, we found that the global parameter "adftools_deployment_state" used to hold the MD5 digest for the objects is causing the request size to increase hitting the limit of ADF. Once the parameter value is reset, we could run the pipelines.

It would be good if there is an option to store the deployment state externally instead of the global parameters. Even if there is an option to provide the deployment state as an input json file, it will help us to utilize the feature without hitting the request payload limits.

**Comment by NowinskiK** [comment]
Thanks @anfredrick for raising this issue. I will check that and consider suggested alternative.
What external storage would be best for your scenario? Azure Storage?

**Comment by MartaUch** [comment]
Hi Kamil :)
I didn't notice this issue before, but I think it's related to the problem I raised recently as well: https://github.com/Azure-Player/azure.datafactory.tools/issues/377. I guess we can connect those two.
Would be really great to have sort of workaround. I was thinking about Azure Storage, SQL table in database..

Thanks!
Marta

**Comment by NowinskiK** [comment]
I tested the behaviour and I can't reproduce this error. What I've done:
- Added artificial 2000 (2k) objects into `adftools_deployment_state` global parameter
- Deployed all GParams including the big one 

Payload sent = **125kB**
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/989eaca5-c3c9-4c00-9dd1-7f99e9f445a0)

All Global Parameters seem to be deployed successfully in target ADF:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/499ecd46-c82f-49c0-8774-96ed45adac9d)

@anfredrick please provide more details of script which enables me to reproduce the error.

**Comment by anfredrick** [comment]
Hi @NowinskiK, Thanks for the update and apologies for the delayed response. 

There is no issue while deploying the parameters. After deployment, if you try to run any pipeline then the pipeline will fail to start with the error as below,

ErrorCode=FlowRunSizeLimitExceeded, ErrorMessage=Triggering the pipeline failed due to large run size. This could happen when a run has a large number of activities or large inputs used in some of the activities, including parameters.

If you could provide an option to write the adftools_deployment_state value into a file (the same file as input for subsequent deployment), it would be relatively simple. We could then decide to store the file into any storage git/azure blob etc., as we need in our deployment pipelines.

**Comment by NowinskiK** [comment]
Thanks @anfredrick. Now, it's totally different Error & from this description, I know what I need to test. I will check that out.

**Comment by NowinskiK** [comment]
I still can't reproduce the issue:
My adf: `BigFactorySample2-7d6cdb5f`

# GP:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/fb4b75f4-a730-43e5-8d04-6f184963c71f)

# Pipeline:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/780c42e5-3c1e-4a15-a5cd-b1d9c293c95b)

# Debug run:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/638d5b27-8610-4683-b3f8-385600e04d55)

# Trigger run:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/4638fe27-3262-4475-85ec-75e620076fcb)

What am I missing?

**Comment by NowinskiK** [comment]
Thanks @MartaUch & @chalabaj for additional feedback and details.
I'm planning to fix this issue by saving the `adftools_deployment_state` to a storage provided in configuration.
Azure DevOps Agent should have access to a given location, so ADF Global Params won't be affected.
Will that work well?

**Comment by g20yr** [comment]
@NowinskiK 
Can we adftools_deployment_state  to the git itself? This way there is no dependency on storage and adf

**Comment by NowinskiK** [comment]
I don't think so... Repositories (like GIT) are for keeping a source of code, not status(es) of deployments.
Unless I misunderstood your idea.

**Comment by chalabaj** [comment]
@g20yr how large would be the file? if it is > few MB I would rather put it to storage than git.

**Comment by NowinskiK** [comment]
@g20yr , @chalabaj new release will support Storage, not GIT, which is not the right place to keep the deployment statuses.

**Comment by chalabaj** [comment]
> @g20yr , @chalabaj new release will support Storage, not GIT, which is not the right place to keep the deployment statuses.

Perfect. We will gladly test it once it is released.

**Comment by MartaUch** [comment]
Hi @NowinskiK ,
I’m also looking forward to try out the new approach once it’s released. For now workaround that I’ve implemented works fine in our platform, but definitely approach with storage will be much better and cleaner :) 
Thanks!

**Comment by Prefix42** [comment]
Hi @NowinskiK, super keen for the feature and curious if there are any updates. Happy to help out if I can.

**Comment by NowinskiK** [comment]
The public preview version of this (fixed & modified) feature has been released:
https://www.powershellgallery.com/packages/azure.datafactory.tools/1.10.1-preview
@chalabaj @MartaUch @Prefix42 @g20yr - please test it and send me feedback here.

**Comment by NowinskiK** [comment]
Public Release v.1.11.0
