### ISSUE TITLE
ADF pipelines cannot be executed due to big size of global parameter: adftools_deployment_state

### ISSUE THREAD

**Issue by MartaUch** [Azure-Player/azure.datafactory.tools#377]
Hello,

Today we enabled "Incremental Deployment" feature and we were not able to run our pipelines due to big size of adftools_deployment_state global parameter. When we removed that, all the pipelines have run successfully. 
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/2496c155-e154-4dd2-a944-c0958e5be8e0)

Value of this global parameter is not used anywhere. Are there any work arounds for such a big adf instances? Are there any limitations we should keep in mind?

It's confusing, because I was able to recreate and publish such a global parameter even manually and there was no issue.
I created a ticket for Microsoft already, but just wanted to raise it here because maybe someone else can run into the similar issue.

Thank you for your support!

**Comment by NowinskiK** [comment]
Thanks Marta. Closing this as duplicated of #374
