### ISSUE TITLE
Question regarding managed system identity (MSI) 

### ISSUE THREAD

**Issue by Mishco** [Azure-Player/azure.datafactory.tools#379]
**Describe the bug**
Is there a way to enable managed identity via adftools automatically ? 

**To Reproduce**
Right now we are trying to create ADF automatically, but there is manual input necessary for that step. Do you have some suggestions how to achieve that ? 

**Expected behaviour**
Enabled MSI 

**Screenshots**
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/17578897/9dce5dbb-196f-4b90-a946-8036a8c2cab6)

**Comment by NowinskiK** [comment]
Maybe I'm missing something here, but right now when you create a new instance of ADF within #adftools MSI is enabled.
Please check this code:
[adhoc/issue-379/issue-379.ps1](https://github.com/Azure-Player/azure.datafactory.tools/blob/5f349da00c402c40f582e30b3d8db4c7ed6c53f0/adhoc/issue-379/issue-379.ps1)

and result below:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/780b378f-db07-4d01-b446-04879fd3cd1b)
