### ISSUE TITLE
Unable to use `$.` to refer to the root of the JSON

### ISSUE THREAD

**Issue by camilo-s** [Azure-Player/azure.datafactory.tools#383]
**Describe the bug**
I'm trying to use the `$.` syntax to replace the name of the data factory object by setting the path from the root of the JSON. However, I get the following error:
```
     | ADFT0010: Wrong path defined in config for object(path):
     | factory.adf-trial-dev(properties.$.name)
``` 

**To Reproduce**
I'm passing a `config-qa.csv` file with the following content:
```
type,name,path,value
factory,adf-trial-dev,$.name,adf-trial-qa
```

**Expected behaviour**
I would expect the path to be parsed correctly starting from the root when prepending it with `$`.

Looking at the source for [Update-PropertiesForObject](https://github.com/Azure-Player/azure.datafactory.tools/blob/071dcd8648b1acbe30973b9e89d642752b7d70d2/private/Update-PropertiesFromFile.ps1#L115) though, it seems the `$path` variable is always adjoined to the `properties` node, making it impossible to actually target the JSON's root node.

**Version of PowerShell module of:**
 - ver1.8.000

**Provide all files to reproduce the issue**
- Gist with log file: https://gist.github.com/camilo-s/756c023a8597df8ed01867a8b99232cc

**Comment by NowinskiK** [comment]
The tool doesn't support renaming ADF's objects, hence it's not possible to change `name` property in files.
