### ISSUE TITLE
Publish GlobalParams fail when globalConfigurations exist but Global Params list is empty

### ISSUE THREAD

**Issue by ederfdias** [Azure-Player/azure.datafactory.tools#387]
I am trying to run a pipeline like this:

- task: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1
      displayName: 'publish to ${{ parameters.dataFactoryName }} adf in env ${{ parameters.branch }}'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        ResourceGroupName: ${{ parameters.resourceGroupName }}
        DataFactoryName: ${{ parameters.dataFactoryName }}
        DataFactoryCodePath: '$(System.DefaultWorkingDirectory)/dataFactory'
        Location: ${{ parameters.location }}
        StageType: FilePath
        StageConfigFile: '$(System.DefaultWorkingDirectory)/dataOps/configs/${{ parameters.branch }}.csv'
        DeleteNotInSource: true
        CreateNewInstance: false
        PublishMethod: 'AzResource'
        IgnoreLackOfReferencedObject: true
        TriggerStartMethod: KeepPreviousState

It was running fine some days ago, but now start to stop with the error below:

Adding global parameter...
##[error]You cannot call a method on a null-valued expression.

I double check permission, variables, etc.
The only thing was changed is that we create a new Data Factory resource.

One interest thing is even reporting an error the o check ADF in live mode and the pipelines is deployed.

Any guess?

**Comment by ederfdias** [comment]
Thank you all

**Comment by ederfdias** [comment]
@NowinskiK do you know if there plan to apply the same solution here in this repo below?
https://github.com/Azure-Player/azure.datafactory.devops

I just noted that we have installed that extension from marketplace:
https://marketplace.visualstudio.com/items?itemName=SQLPlayer.DataFactoryTools

I think it uses this tools somehow.

**Comment by NowinskiK** [comment]
Yes, this PowerShell module is fully used by DevOps Extension. 
Somehow I missed updating to v1.9. I will do that tonight.

**Comment by NowinskiK** [comment]
Released: https://github.com/Azure-Player/azure.datafactory.devops/releases/tag/v1.33
Version: 1.33.1471 (marketplace)
