### ISSUE TITLE
Test-AdfCode fails when using pwsh inside a docker image

### ISSUE THREAD

**Issue by cristianastorino** [Azure-Player/azure.datafactory.tools#394]
**Describe the bug**
While executing the Test-AdfCode cmdlet, I'm receiving the following error:

```
=== Loading files from location: /tmp/ADFDev2/ ...
IntegrationRuntimes: 0 object(s) loaded.
LinkedServices: 1 object(s) loaded.
Pipelines: 2 object(s) loaded.
DataSets: 1 object(s) loaded.
DataFlows: 0 object(s) loaded.
Triggers: 0 object(s) loaded.
Managed VNet: 0 object(s) loaded.
Managed Private Endpoints: 0 object(s) loaded.
Credentials: 0 object(s) loaded.
Factories: 0 object(s) loaded.
=== Validating files ...
Checking: [linkedService].[AzureDataLakeStorage1]...
Checking: [pipeline].[pipeline1]...
Checking: [pipeline].[pipeline2]...
Checking: [dataset].[Parquet1]...
=== Validating other rules ...
Checking duplicated names...
Checking names of linkedservices, datasets, dataflows...
Checking: Global parameter names...
=== Validating config files ...
Get-ChildItem: /root/.local/share/powershell/Modules/azure.datafactory.tools/1.9.0/public/Test-AdfCode.ps1:121
Line |
 121 |  …    $files = Get-ChildItem -Path $filePattern -Include '*.csv','*.json …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot process argument because the value of argument "path" is not valid. Change the value of the "path" argument and run the operation again.
ERROR: The property 'FullName' cannot be found on this object. Verify that the property exists.
```

looks like the problem is on that line: https://github.com/Azure-Player/azure.datafactory.tools/blob/master/public/Test-AdfCode.ps1#L121

if I execute the following command inside a linux docker image with powershell installed, I'm getting the exact same error:

```
Get-ChildItem -Path $null -Include '*.csv','*.json'
Get-ChildItem: Cannot process argument because the value of argument "path" is not valid. Change the value of the "path" argument and run the operation again.
```

but if I do the same on a windows PS, I get no errors:

```
Get-ChildItem -Path $null -Include '*.csv','*.json'
```

**To Reproduce**
Have `pwsh` installed inside a linux docker image. I'm using this version:
```
PS /> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      2
```

**Expected behaviour**
No error is returned

**Version of PowerShell module of:**
 - ver 1.9.0

**Comment by NowinskiK** [comment]
What value do you provide for `$ConfigPath` input parameter? Line 116 resets the `$filePattern` variable when the file doesn't exist in 'deployment' folder. I'll add additional logs in debug mode, but check all paths and files you're pointing.

**Comment by cristianastorino** [comment]
Actually I'm not passing $ConfigPath

**Comment by NowinskiK** [comment]
Thanks for all the details and references. 
I believe the problem is with `Path` parameter being `$null`. Weird, but it works fine with PS 5.1 and even in 7.4.2:
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/25029325/88ffaa0c-d520-424c-81f0-f2caec432501)

**Comment by cristianastorino** [comment]
My suspect is that in your case is not throwing because your current work directory is `/home/kamil`. Can you try with:

```
PS /> cd /
PS /> Get-ChildItem -Path $null -Include '*.csv','*.json'
```

I'm not sure of the reason why when the working directory is `/` it throws, maybe because of symbolic links.

Anyway, I think `Get-ChildItem` should be called only if `$path` is not `$null`, else you risk to read csv or json that are in your current working directory and are not part of your configuration
