### ISSUE TITLE
##[error]The remote server returned an error: (404) Not Found. Incremental Deployment

### ISSUE THREAD

**Issue by bretvert** [Azure-Player/azure.datafactory.tools#395]
**Describe the bug**
When I activate incremental deployment, I receive the following error message:
##[error]The remote server returned an error: (404) Not Found.

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/819d257b-aca0-4aaa-a262-9ab9bf2eccae)

**To Reproduce**
The incremental deployment should proceed without errors, successfully deploying the necessary changes.
``

**Screenshots**
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/80c4947f-16ac-4570-a0b2-517ce3560251)

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/c6058841-68bf-4049-b29e-9b85abaaa912)

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/121a1699-22c7-4ac0-8d25-8e7bbe9389c2)
**Version of PowerShell module of:**
 - ver 1 of sql player

**Comment by bretvert** [comment]
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/8066223f-1c75-46cc-adec-bf23252cd41e)

**Comment by NowinskiK** [comment]
Please provide the whole log.

**Comment by NowinskiK** [comment]
The `HTTP 404 Not Found` response status code indicates that the server cannot find the requested resource. 
Do validate all parameters you provide in the task (ADF Name, Resource Group, Subscription).
I can't replicate this error. Very likely it's something on your side only.
