### ISSUE TITLE
[IntegrationRuntime].[AutoResolveIntegrationRuntime] was not found

### ISSUE THREAD

**Issue by GioSebis** [Azure-Player/azure.datafactory.tools#407]
**Describe the bug**
Pipeline fails with the error message "[IntegrationRuntime].[AutoResolveIntegrationRuntime] was not found"
This always happens when I have a linkedService with the default "AutoResolveIntegrationRuntime".

**To Reproduce**
Your script to reproduce the behaviour:

My pipeline:
```
stages:
- stage: PublishToProd
  jobs:
  - job: PublishToProd
    steps:
    - task: AzurePowerShell@4
      displayName: 'Azure PowerShell script: InlineScript'
      inputs:
        azureSubscription: '...'
        azurePowerShellVersion: 'LatestVersion'
        ScriptType: 'InlineScript' 
        Inline: |
          Write-Host "Install Az.Resources"
          Install-Module -Name Az.Resources -AllowClobber -Scope CurrentUser
          Write-Host "Start adf deployment"
          $ResourceGroupName = '...'
          $DataFactoryName = "..."
          $Location = "westeurope"
          $RootFolder = '$(System.DefaultWorkingDirectory)'
          $opt = New-AdfPublishOption
          $opt.CreateNewInstance = $false
          $opt.DeleteNotInSource = $false
          $opt.FailsWhenPathNotFound = $false
          $opt.Excludes.Add("integrationruntime. ...shir", "")
          $opt.Excludes.Add("integrationruntime. ...shir", "")
          $opt.Excludes.Add("managedVirtualNetwork*.*", "")
          Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location" -Option $opt -Stage "prod"
```

linkedService JSON snippet in adf:
```
{
    "name": "ls_test",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "parameters": {
            "p_cluster": {
                "type": "string"
            },
            "p_database": {
                "type": "string"
            }
        },
        "annotations": [],
        "type": "AzureDataExplorer",
        "typeProperties": {
            "endpoint": "@linkedService().p_cluster",
            "database": "@linkedService().p_database"
        },
        "description": "Linked service to Azure Data Explorer. Requires cluster and database name parameters as input."
    }
}
```
Same linkedService JSON snippet in devops:
```
{
	"name": "ls_test",
	"properties": {
		"parameters": {
			"p_cluster": {
				"type": "string"
			},
			"p_database": {
				"type": "string"
			}
		},
		"annotations": [],
		"type": "AzureDataExplorer",
		"typeProperties": {
			"endpoint": "@linkedService().p_cluster",
			"database": "@linkedService().p_database"
		},
		"connectVia": {
			"referenceName": "AutoResolveIntegrationRuntime",
			"type": "IntegrationRuntimeReference"
		},
		"description": "Linked service to Azure Data Explorer. Requires cluster and database name parameters as input."
	}
}
```

**As you can see, connectVia { ... } is only defined in the devops json, but not in adf directly. In this case there is always an error.**

**Expected behaviour**
Deploy the linkedservices with "AutoResolveIntegrationRuntime" in the same way as the linkedServices with a different IR.

**Screenshots**
![image](https://github.com/user-attachments/assets/0b8debec-4839-402f-8098-33133e6a14dc)

**Version of PowerShell module of:**
 - Version 1.9.001

**Provide all files to reproduce the issue**

**Comment by NowinskiK** [comment]
I've never seen this block when **AutoResolveIntegrationRuntime** was used:
```
"connectVia": {
    "referenceName": "AutoResolveIntegrationRuntime",
    "type": "IntegrationRuntimeReference"
},
```
I see you created a Linked Service to Azure Data Explorer cluster.
In my own environment, I created the same and the block doesn't appear:
{
    "name": "LS_AzureDataExplorer1",
    "properties": {
        "annotations": [],
        "type": "AzureDataExplorer",
        "typeProperties": {
            "endpoint": "https://adeclu.uksouth.kusto.windows.net",
            "database": "abc"
        }
    }
}

If your case is different - I'd suggest two ways:
1) Create a ticket to MS support (this may takes few weeks) OR
2) Just remove the block from the LS (from JSON file in code repository)
