### ISSUE TITLE
Azure SSIS IR with Custom Setup Script fails to start since latest release of ADF Tools

### ISSUE THREAD

**Issue by mvdwielen** [Azure-Player/azure.datafactory.tools#429]
**Describe the bug**
In our environment we have an Azure SSIS IR configured with a custom setup script stored on a storage account.
The storage account is accessed via a SAS URI which you need to provide during the setup of the Azure SSIS IR.
In our release pipeline we use ADF tools to replace the SAS URI of the Azure SSIS IR with a secret value stored in keyvault,

Until 6-11-2024 this process has been working fine but since then the provisioning of the Azure SSIS IR fails with error:
[{"Code":"CustomSetupScriptBlobContainerInaccessible","NodeNumber":1,"Message":"Operation failed to due to storage exception: The remote server returned an error: (409) Conflict.. (Http error: 409, Public access is not permitted on this storage account. Request Id to storage: ......)"}]

We have created a ticket with Microsoft support and they confirmed the error message is misleading, the issue is that an invalid SAS URI is used and most likely this is due to the fact that ADF tools is replacing the value of the json path: integrationRuntime,ssis-ir,typeProperties.ssisProperties.customSetupScriptProperties.sasToken.value,"$($Env:keyvault_secret_name)" with a different value then it was doing so before.

The only way to solve the issue below was removing the inline replacement of the json path in the IR.json definition from the release pipeline and just manually set it via Azure Data Factory UI and then leave it untouched.

We are running ADF tools on a self hosted azure agent and we have upgraded Powershell on that agent as the latest version of ADF Tools requires Az.Account 3.0.4

- We have tested if there could be an issue with the SAS URI by connecting to the blob container using the SAS URI with azure storage explorer, this test succeeded.
- We have checked if any change in the code or platform code be the reason why this suddenly fails and confirmed no changes were made except a new version of ADF tools is used and the Powershell modules have been upgraded on the Self Hosted Azure DevOps Agent.

**To Reproduce**
Setup an ADF
Setup a Storage Account with a blob container and a SAS URI with rcwl access
Create a main.cmd file in the container with a simple echo statement
Create an Azure SSIS IR with a custom setup script and set the SAS URI

Consult: https://learn.microsoft.com/en-us/azure/data-factory/how-to-configure-azure-ssis-ir-custom-setup to understand how to accomplish this.

Create a secret in keyvault with the secret part of the SAS URI (the value after the ? in the SAS URI)
Create a release pipeline
Get the secret from keyvault
Ensure ADF Tools replaces the json path: typeProperties.ssisProperties.customSetupScriptProperties.sasToken.value with the value retreived from keyvault
Publish ADF with ADF Tools
Start the Integration Runtime

Starting the IR will result in error:
[{"Code":"CustomSetupScriptBlobContainerInaccessible","NodeNumber":1,"Message":"Operation failed to due to storage exception: The remote server returned an error: (409) Conflict.. (Http error: 409, Public access is not permitted on this storage account. Request Id to storage: ......)"}]

**Expected behaviour**
The SAS URI should be replaced with the plain text value received from the secret stored in Keyvault for the Azure SSIS IR.
The Azure SSIS IR should start succesfully

**Version of PowerShell module of:**
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
3.0.4                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts ...
2.0.1                Az.Advisor                          PSGallery            Microsoft Azure PowerShell: Advisor cm...
6.0.4                Az.Aks                              PSGallery            Microsoft Azure PowerShell - Azure man...
1.1.5                Az.AnalysisServices                 PSGallery            Microsoft Azure PowerShell - Analysis ...
4.0.4                Az.ApiManagement                    PSGallery            Microsoft Azure PowerShell - Api Manag...
1.1.0                Az.App                              PSGallery            Microsoft Azure PowerShell: App cmdlets
1.3.2                Az.AppConfiguration                 PSGallery            Microsoft Azure PowerShell: AppConfigu...
2.2.5                Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell: Applicatio...
1.0.1                Az.ArcResourceBridge                PSGallery            Microsoft Azure PowerShell: ArcResourc...
2.0.2                Az.Attestation                      PSGallery            Microsoft Azure PowerShell - Attestati...
1.0.2                Az.Automanage                       PSGallery            Microsoft Azure PowerShell: Automanage...
1.10.0               Az.Automation                       PSGallery            Microsoft Azure PowerShell - Automatio...
3.6.3                Az.Batch                            PSGallery            Microsoft Azure PowerShell - Batch ser...
2.1.0                Az.Billing                          PSGallery            Microsoft Azure PowerShell - Billing s...
3.2.2                Az.Cdn                              PSGallery            Microsoft Azure PowerShell: Cdn cmdlets
2.0.1                Az.CloudService                     PSGallery            Microsoft Azure PowerShell: CloudServi...
1.14.1               Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive...
8.4.0                Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute s...
1.0.1                Az.ConfidentialLedger               PSGallery            Microsoft Azure PowerShell: Confidenti...
4.0.2                Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell: ContainerI...
4.2.1                Az.ContainerRegistry                PSGallery            Microsoft Azure PowerShell - Container...
1.15.0               Az.CosmosDB                         PSGallery            Microsoft Azure PowerShell - CosmosDB ...
1.1.1                Az.DataBoxEdge                      PSGallery            Microsoft Azure PowerShell - DataBoxEd...
1.9.0                Az.Databricks                       PSGallery            Microsoft Azure PowerShell: Databricks...
1.18.8               Az.DataFactory                      PSGallery            Microsoft Azure PowerShell - Data Fact...
1.0.3                Az.DataLakeAnalytics                PSGallery            Microsoft Azure PowerShell - Data Lake...
1.3.2                Az.DataLakeStore                    PSGallery            Microsoft Azure PowerShell - Azure Dat...
2.4.0                Az.DataProtection                   PSGallery            Microsoft Azure PowerShell: DataProtec...
1.0.2                Az.DataShare                        PSGallery            Microsoft Azure PowerShell - DataShare...
4.3.1                Az.DesktopVirtualization            PSGallery            Microsoft Azure PowerShell: DesktopVir...
1.2.0                Az.DevCenter                        PSGallery            Microsoft Azure PowerShell: DevCenter ...
1.0.3                Az.DevTestLabs                      PSGallery            Microsoft Azure PowerShell - DevTest L...
1.2.1                Az.Dns                              PSGallery            Microsoft Azure PowerShell - DNS servi...
6.2.0                Az.KeyVault                         PSGallery            Microsoft Azure PowerShell - Key Vault...
7.5.0                Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Res...
7.4.0                Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage s...
1.4.8.1              PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a...
2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for di...

**Comment by NowinskiK** [comment]
Thanks @mvdwielen for using the tool.
I don't believe the issue happens due to #adftools PS module. 
In the latest version were no changes to the token replacement mechanism.
Enable "diagnostic settings" to see verbose output in the log, so you can troubleshoot better. Also, provide the log here. 
Currently, I can't see where PS module can fail in this matter. If that is the case - this would not work for thousands of organisations worldwide.
Thanks for providing detailed steps to reproduce, but that's too much. You should only focus on SAS URI and check whether it has been updated or not.

**Comment by NowinskiK** [comment]
Maybe try to install and import the previous version of PS module to ensure it works as previously? 
That would be a quick and non-time-consuming task.
